{{- $fullName := include "capi.fullname" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullName }}-ext-leader

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullName }}-ext-leader
subjects:
  - kind: ServiceAccount
    name: {{ $fullName }}-ext
    namespace: {{ .Release.Namespace }}

