{{- $fullName := include "kubernetes.fullname" . -}}
{{- $certName := include "kubernetes.certname" . -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: '{{ $fullName }}-pki-admin-client'

spec:
  commonName: '{{ $certName }}-admin-client'

  duration: 8760h0m0s

  issuerRef:
    kind: Issuer
    name: '{{ $fullName }}-issuer'

  renewBefore: 4380h0m0s

  secretName: '{{ $fullName }}-pki-admin-client'

  subject:
    organizations:
      - 'system:masters'

  usages:
    - signing
    - key encipherment
    - client auth
