{{- if and .Values.kubernetes.apiServer.enabled .Values.kubernetes.apiServer.service.enabled }}

apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-name: k0s-kubeapi
    metallb.universe.tf/allow-shared-ip: k0s-api
  labels:
    app: infra1-dc1-infra-k0s-k8s-kubernetes-apiserver
  name: infra1-dc1-infra-k0s-k8s-kubernetes-apiserver
  namespace: core-prod
spec:
  type: {{ .Values.kubernetes.apiServer.service.type }}
  {{- with .Values.kubernetes.apiServer.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}

  allocateLoadBalancerNodePorts: true

  ipFamilies:
    - IPv4

  ipFamilyPolicy: SingleStack


  {{- with .Values.kubernetes.apiServer.service.externalIPs }}
  externalIPs:
  {{- range . }}
    - {{ . }}
  {{- end }}
  {{- end }}

  ports:
    - name: client

      targetPort: client
      port: 6443

      protocol: TCP
      appProtocol: https


    - name: client-https

      targetPort: client
      port: 443

      protocol: TCP
      appProtocol: https


  selector:
    app: infra1-dc1-infra-k0s-k8s-kubernetes-apiserver

  publishNotReadyAddresses: true
  sessionAffinity: ClientIP


{{- end }}
