apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-name: k0s-kubeapi

  labels:
    app: infra1-dc1-infra-k0s-k8s-kubernetes-apiserver
  name: infra1-dc1-infra-k0s-k8s-kubernetes-apiserver
  namespace: core-prod
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.18.213.183
  clusterIPs:
    - 172.18.213.183
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 10.1.1.40
  ports:
    - name: client
      port: 6443
      protocol: TCP
      targetPort: 6443
    - name: client-https
      port: 443
      protocol: TCP
      targetPort: 6443
    - name: agent
      port: 8132
      protocol: TCP
      targetPort: agent
  selector:
    app: infra1-dc1-infra-k0s-k8s-kubernetes-apiserver
  sessionAffinity: None
  type: LoadBalancer

