apiVersion: v1
data:
  egress-selector-configuration.yaml: |
    apiVersion: apiserver.k8s.io/v1beta1
    kind: EgressSelectorConfiguration
    egressSelections:
    - name: cluster
      connection:
        proxyProtocol: GRPC
        transport:
          uds:
            udsName: /run/konnectivity-server/konnectivity-server.socket
    - name: master
      connection:
        proxyProtocol: Direct
    - name: etcd
      connection:
        proxyProtocol: Direct
kind: ConfigMap
metadata:
  name: infra1-dc1-infra-k0s-k8s-kubernetes-apiserver-config
  namespace: core-prod
