apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-name: k0s-kubeapi
    metallb.universe.tf/allow-shared-ip: k0s-api
  labels:
    app: infra1-dc1-infra-k0s-k8s-kubernetes-apiserver
  name: infra1-dc1-infra-k0s-k8s-kubernetes-apiserver
  namespace: core-prod
spec:
  allocateLoadBalancerNodePorts: true

  ipFamilies:
    - IPv4

  ipFamilyPolicy: SingleStack

  loadBalancerIP: 10.1.1.40

  externalIPs:
    - 10.0.8.1

  ports:
    - name: client

      targetPort: client
      port: 6443

      protocol: TCP
      appProtocol: https

    - name: client-https

      targetPort: client
      port: 443

      protocol: TCP
      appProtocol: https

  selector:
    app: infra1-dc1-infra-k0s-k8s-kubernetes-apiserver
  publishNotReadyAddresses: true
  sessionAffinity: ClientIP
  type: LoadBalancer

