{{- $fullName := include "kubernetes.fullname" . -}}
{{- $ipAddress := include "kubernetes.getKonnectivityAddress" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-apiserver-config

data:
  egress-selector-configuration.yaml: |
    apiVersion: apiserver.k8s.io/v1alpha1

    kind: EgressSelectorConfiguration

    egressSelections:
      - name: cluster
        connection:
          proxyProtocol: Direct

      - name: controlplane
        connection:
          proxyProtocol: Direct

      - name: etcd
        connection:
          proxyProtocol: Direct

