{{- $fullName := include "kubernetes.fullname" . -}}
{{- $apiAddress := include "kubernetes.getAPIHostnamePort" . -}}
---
apiVersion: v1
kind: ConfigMap

metadata:
  name: infra1-dc1-infra-k0s-k8s-kubernetes-controller-manager-conf
  namespace: core-prod

data:
  controller-manager.conf: |
    apiVersion: v1
    kind: Config

    clusters:
      - cluster:
          certificate-authority: /pki/controller-manager-client/ca.crt
          server: https://{{ $apiAddress }}
        name: default-cluster

    contexts:
      - context:
          cluster: default-cluster
          namespace: default
          user: default-auth
        name: default-context

    current-context: default-context

    preferences: {}
    users:
      - name: default-auth
        user:
          client-certificate: /pki/controller-manager-client/tls.crt
          client-key: /pki/controller-manager-client/tls.key
