apiVersion: v1
kind: Service
metadata:
  labels:
    app: infra1-dc1-infra-k0s-k8s-kubernetes-controller-manager

  name: infra1-dc1-infra-k0s-k8s-kubernetes-controller-manager
  namespace: core-prod
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack

  ports:
    - name: client

      targetPort: client
      port: 10257

      protocol: TCP

  selector:
    app: infra1-dc1-infra-k0s-k8s-kubernetes-controller-manager

  sessionAffinity: None
  type: ClusterIP

