
{{- if and .Values.kubernetes.controllerManager.enabled .Values.kubernetes.controllerManager.service.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $fullName }}-controller-manager

  name: {{ $fullName }}-controller-manager

spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack

  ports:
    - name: https

      targetPort: https
      port: {{ .Values.kubernetes.controllerManager.service.port }}

      protocol: TCP

  selector:
    app: {{ $fullName }}-controller-manager

  sessionAffinity: None
  type: ClusterIP
{{- end }}
