
{{- if and .Values.kubernetes.controllerManager.enabled .Values.kubernetes.controllerManager.service.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-controller-manager

  labels:
    app: {{ $fullName }}-controller-manager

    {{- with .Values.kubernetes.controllerManager.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  {{- with .Values.kubernetes.controllerManager.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.kubernetes.controllerManager.service.type }}
  {{- with .Values.kubernetes.controllerManager.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}

  ports:
    - name: https

      targetPort: https
      port: {{ .Values.kubernetes.controllerManager.service.port }}

      protocol: TCP

  selector:
    app: {{ $fullName }}-controller-manager
{{- end }}
