{{- $fullName := include "kubernetes.fullname" . -}}
{{- $certName := include "kubernetes.certname" . -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infra1-dc1-infra-k0s-k8s-kubernetes-pki-controller-manager-server
  namespace: core-prod
spec:

  commonName: infra1-dc1-infra-k0s-k8s-kubernetes-controller-manager-server

  dnsNames:
    - infra1-dc1-infra-k0s-k8s-kubernetes-controller-manager
    - infra1-dc1-infra-k0s-k8s-kubernetes-controller-manager.core-prod
    - infra1-dc1-infra-k0s-k8s-kubernetes-controller-manager.core-prod.svc
    - infra1-dc1-infra-k0s-k8s-kubernetes-apiserver.core-prod.svc.cluster.local
    - infra1-dc1-infra-k0s-k8s-kubernetes-apiserver.core-prod.svc.cluster
    - localhost
    - k0s-kubeapi.service.dc1.kjdev
    - k0s-kubeapi.service.kjdev
    - api.k0s.dc1.resolvemy.host
    - kubernetes.default
    - kubernetes.default.svc
    - kubernetes.default.svc.cluster.local
    - kubernetes.default.svc.cluster

  duration: 8760h0m0s

  ipAddresses:
    - 127.0.0.1
    - 10.0.8.1
    - 172.18.213.183
    - 10.1.1.40

  issuerRef:
    kind: Issuer
    name: infra1-dc1-infra-k0s-k8s-kubernetes-issuer

  renewBefore: 4380h0m0s

  secretName: infra1-dc1-infra-k0s-k8s-kubernetes-pki-controller-manager-server

  subject:
    organizations:
      - infra1-dc1-infra-k0s-k8s-kubernetes

  usages:
    - signing
    - key encipherment
    - server auth
