{{- $fullName := include "kubernetes.fullname" . -}}
{{- $certName := include "kubernetes.certname" . -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-pki-controller-manager-client

spec:
  commonName: 'system:kube-controller-manager'
  
  issuerRef:
    kind: Issuer
    name: '{{ $fullName }}-issuer'
  
  duration: 8760h0m0s
  renewBefore: 4380h0m0s
  
  secretName: {{ $fullName }}-pki-controller-manager-client
  
  subject:
    organizations:
      - 'system:kube-controller-manager'
  
  usages:
    - signing
    - key encipherment
    - client auth

