{{- if .Values.etcd.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
{{- $certName := include "kubernetes.certname" . -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-pki-etcd-peer

spec:
  commonName: {{ $certName }}-etcd-peer
  dnsNames:
    - infra1-dc1-infra-k0s-k8s-kubernetes-etcd
    - infra1-dc1-infra-k0s-k8s-kubernetes-etcd.core-prod
    - infra1-dc1-infra-k0s-k8s-kubernetes-etcd.core-prod.svc
    - infra1-dc1-infra-k0s-k8s-kubernetes-etcd.core-prod.svc.cluster
    - infra1-dc1-infra-k0s-k8s-kubernetes-etcd.core-prod.svc.cluster.local
    - '*.infra1-dc1-infra-k0s-k8s-kubernetes-etcd'
    - '*.infra1-dc1-infra-k0s-k8s-kubernetes-etcd.core-prod'
    - '*.infra1-dc1-infra-k0s-k8s-kubernetes-etcd.core-prod.svc'
    - '*.infra1-dc1-infra-k0s-k8s-kubernetes-etcd.core-prod.svc.cluster'
    - '*.infra1-dc1-infra-k0s-k8s-kubernetes-etcd.core-prod.svc.cluster.local'
    - localhost

  duration: 8760h0m0s

  ipAddresses:
    - 127.0.0.1

  issuerRef:
    kind: Issuer
    name: {{ $fullName }}-etcd-issuer

  renewBefore: 4380h0m0s

  secretName: {{ $fullName }}-pki-etcd-peer

  subject:
    organizations:
      - {{ $fullName }}

  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
{{- end -}}