apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: infra1-dc1-infra-k0s-k8s-kubernetes-etcd
    argocd.argoproj.io/instance: infra1-dc1-infra-k0s-k8s
  name: infra1-dc1-infra-k0s-k8s-kubernetes-etcd
  namespace: core-prod
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: infra1-dc1-infra-k0s-k8s-kubernetes-etcd
  serviceName: infra1-dc1-infra-k0s-k8s-kubernetes-etcd
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2022-05-12T16:09:11Z'
      creationTimestamp: null
      labels:
        app: infra1-dc1-infra-k0s-k8s-kubernetes-etcd
      name: infra1-dc1-infra-k0s-k8s-kubernetes-etcd
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: infra1-dc1-infra-k0s-k8s-kubernetes-etcd
                topologyKey: kubernetes.io/hostname
              weight: 1
      automountServiceAccountToken: false
      containers:
        - command:
            - etcd
            - >-
              --advertise-client-urls=https://$(POD_NAME).infra1-dc1-infra-k0s-k8s-kubernetes-etcd:2379
            - '--cert-file=/pki/etcd/server/tls.crt'
            - '--client-cert-auth=true'
            - '--data-dir=/var/lib/etcd'
            - >-
              --initial-advertise-peer-urls=https://$(POD_NAME).infra1-dc1-infra-k0s-k8s-kubernetes-etcd:2380
            - >-
              --initial-cluster=infra1-dc1-infra-k0s-k8s-kubernetes-etcd-0=https://infra1-dc1-infra-k0s-k8s-kubernetes-etcd-0.infra1-dc1-infra-k0s-k8s-kubernetes-etcd:2380,infra1-dc1-infra-k0s-k8s-kubernetes-etcd-1=https://infra1-dc1-infra-k0s-k8s-kubernetes-etcd-1.infra1-dc1-infra-k0s-k8s-kubernetes-etcd:2380,infra1-dc1-infra-k0s-k8s-kubernetes-etcd-2=https://infra1-dc1-infra-k0s-k8s-kubernetes-etcd-2.infra1-dc1-infra-k0s-k8s-kubernetes-etcd:2380
            - '--initial-cluster-state=new'
            - '--initial-cluster-token=infra1-dc1-infra-k0s-k8s-kubernetes-etcd'
            - '--key-file=/pki/etcd/server/tls.key'
            - '--listen-client-urls=https://0.0.0.0:2379'
            - '--listen-peer-urls=https://0.0.0.0:2380'
            - '--listen-metrics-urls=http://0.0.0.0:2381'
            - '--name=$(POD_NAME)'
            - '--peer-cert-file=/pki/etcd/peer/tls.crt'
            - '--peer-client-cert-auth=true'
            - '--peer-key-file=/pki/etcd/peer/tls.key'
            - '--peer-trusted-ca-file=/pki/etcd/ca/tls.crt'
            - '--snapshot-count=10000'
            - '--trusted-ca-file=/pki/etcd/ca/tls.crt'
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: ETCDCTL_API
              value: '3'
            - name: ETCDCTL_CACERT
              value: /pki/etcd/peer/ca.crt
            - name: ETCDCTL_CERT
              value: /pki/etcd/peer/tls.crt
            - name: ETCDCTL_KEY
              value: /pki/etcd/peer/tls.key
            - name: ETCDCTL_ENDPOINTS
              value: >-
                https://infra1-dc1-infra-k0s-k8s-kubernetes-etcd-0.infra1-dc1-infra-k0s-k8s-kubernetes-etcd:2379,https://infra1-dc1-infra-k0s-k8s-kubernetes-etcd-1.infra1-dc1-infra-k0s-k8s-kubernetes-etcd:2379,https://infra1-dc1-infra-k0s-k8s-kubernetes-etcd-2.infra1-dc1-infra-k0s-k8s-kubernetes-etcd:2379
          image: 'k8s.gcr.io/etcd:3.5.1-0'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 8
            httpGet:
              path: /health
              port: 2381
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          name: etcd
          ports:
            - containerPort: 2379
              name: client
              protocol: TCP
            - containerPort: 2380
              name: peer
              protocol: TCP
            - containerPort: 2381
              name: metrics
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /pki/etcd/ca
              name: pki-etcd-certs-ca
            - mountPath: /pki/etcd/peer
              name: pki-etcd-certs-peer
            - mountPath: /pki/etcd/server
              name: pki-etcd-certs-server
            - mountPath: /var/lib/etcd
              name: etcd-data
            - mountPath: /backup/snapshot.db
              name: etcd-snapshot
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
        - name: pki-etcd-certs-ca
          secret:
            defaultMode: 420
            secretName: infra1-dc1-infra-k0s-k8s-kubernetes-pki-etcd-ca
        - name: pki-etcd-certs-peer
          secret:
            defaultMode: 420
            secretName: infra1-dc1-infra-k0s-k8s-kubernetes-pki-etcd-peer
        - name: pki-etcd-certs-server
          secret:
            defaultMode: 420
            secretName: infra1-dc1-infra-k0s-k8s-kubernetes-pki-etcd-server
        - hostPath:
            path: /mnt/Site1.NAS1.Pool1/Backups/etcd-snapshot.db
            type: File
          name: etcd-snapshot
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        finalizers:
          - kubernetes.io/pvc-protection
        labels:
          app: infra1-dc1-infra-k0s-k8s-kubernetes-etcd
        name: etcd-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
      status:
        phase: Pending

