{{- if .Values.kubernetes.etcd.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $fullName }}-etcd
    helloworld: {{ $fullName }}-etcd

  name: {{ $fullName }}-etcd

spec:
  clusterIP: None

  clusterIPs:
    - None

  internalTrafficPolicy: Cluster

  ipFamilies:
    - IPv4

  ipFamilyPolicy: SingleStack

  ports:
    - name: client

      port: 2379
      targetPort: 2379

      protocol: TCP


    - name: peer

      port: 2380
      targetPort: 2380

      protocol: TCP


    - name: metrics

      port: 2381
      targetPort: 2381

      protocol: TCP


  publishNotReadyAddresses: true

  selector:
    app: {{ $fullName }}-etcd

  sessionAffinity: None

  type: ClusterIP
{{- end }}
