{{- if .Values.kubernetes.etcd.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
{{- $certName := include "kubernetes.certname" . -}}
{{- $domains := splitList ".," (include "kubernetes.domains" .) -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-pki-etcd-peer

spec:
  commonName: {{ $certName }}-etcd-peer
  dnsNames:
    {{ range $domain := splitList ".," (include "kubernetes.domains" .) }}
    {{ $test := $domain | fromJson }}
    - {{ $fullName }}-etcd{{ $test.domains | join "" }}
    - '*.{{ $fullName }}-etcd{{ $test.domains | join "" }}'
    {{ end }}
    - localhost

  duration: 8760h0m0s

  ipAddresses:
    - 127.0.0.1

  issuerRef:
    kind: Issuer
    name: {{ $fullName }}-etcd-issuer

  renewBefore: 4380h0m0s

  secretName: {{ $fullName }}-pki-etcd-peer

  subject:
    organizations:
      - {{ $fullName }}

  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
{{- end -}}