apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"helm.sh/resource-policy":"keep"},"finalizers":["kubernetes.io/pvc-protection"],"labels":{"app":"infra1-dc1-infra-k0s-k8s-kubernetes-etcd","argocd.argoproj.io/instance":"infra1-dc1-infra-k0s-k8s"},"name":"etcd-backup-infra1-dc1-infra-k0s-k8s-kubernetes-etcd","namespace":"core-prod"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}}
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: zfs.csi.openebs.io
    volume.kubernetes.io/storage-provisioner: zfs.csi.openebs.io
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: infra1-dc1-infra-k0s-k8s-kubernetes-etcd
  name: etcd-backup-infra1-dc1-infra-k0s-k8s-kubernetes-etcd
  namespace: core-prod
  resourceVersion: '3787476'
  uid: 820fd3fc-cfe2-4462-979d-993287185a24
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-zfspv-default
  volumeMode: Filesystem
  volumeName: pvc-820fd3fc-cfe2-4462-979d-993287185a24

