apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: infra1-dc1-infra-k0s-k8s-kubernetes-etcd-backup
  name: infra1-dc1-infra-k0s-k8s-kubernetes-etcd-backup
  namespace: core-prod
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        app: infra1-dc1-infra-k0s-k8s-kubernetes-etcd-backup
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: infra1-dc1-infra-k0s-k8s-kubernetes-etcd-backup
        spec:
          affinity:
            podAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        app: infra1-dc1-infra-k0s-k8s-kubernetes-etcd
                    topologyKey: kubernetes.io/hostname
                  weight: 1
          automountServiceAccountToken: false
          containers:
            - command:
                - /bin/sh
                - '-xc'
                - >
                  rtc() { while read k s v; do test "$k" = "rtc_$1" && echo "$v"
                  && break; done </proc/driver/rtc; }

                  etcdctl snapshot save /data/etcd-prod-hosting-$(rtc
                  date)-$(rtc time).db --debug=true
              env:
                - name: ETCDCTL_API
                  value: '3'
                - name: ETCDCTL_CACERT
                  value: /pki/etcd/peer/ca.crt
                - name: ETCDCTL_CERT
                  value: /pki/etcd/peer/tls.crt
                - name: ETCDCTL_KEY
                  value: /pki/etcd/peer/tls.key
                - name: ETCDCTL_ENDPOINTS
                  value: 'infra1-dc1-infra-k0s-k8s-kubernetes-etcd:2379'
              image: 'k8s.gcr.io/etcd:3.5.1-0'
              imagePullPolicy: IfNotPresent
              name: etcd-backup
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /pki/etcd/ca
                  name: pki-etcd-certs-ca
                - mountPath: /pki/etcd/peer
                  name: pki-etcd-certs-peer
                - mountPath: /pki/etcd/server
                  name: pki-etcd-certs-server
                - mountPath: /data
                  name: data
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          terminationGracePeriodSeconds: 30
          volumes:
            - name: pki-etcd-certs-ca
              secret:
                defaultMode: 420
                secretName: infra1-dc1-infra-k0s-k8s-kubernetes-pki-etcd-ca
            - name: pki-etcd-certs-peer
              secret:
                defaultMode: 420
                secretName: infra1-dc1-infra-k0s-k8s-kubernetes-pki-etcd-peer
            - name: pki-etcd-certs-server
              secret:
                defaultMode: 420
                secretName: infra1-dc1-infra-k0s-k8s-kubernetes-pki-etcd-server
            - name: data
              persistentVolumeClaim:
                claimName: etcd-backup-infra1-dc1-infra-k0s-k8s-kubernetes-etcd
  schedule: 0 */12 * * *
  successfulJobsHistoryLimit: 3
  suspend: false

