apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-backup-infra1-dc1-infra-k0s-k8s-kubernetes-etcd

  labels:
    app: infra1-dc1-infra-k0s-k8s-kubernetes-etcd

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-zfspv-default
