apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"cert-manager.io/v1","kind":"Certificate","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"infra1-dc1-infra-k0s-k8s"},"name":"infra1-dc1-infra-k0s-k8s-kubernetes-pki-front-proxy-ca","namespace":"core-prod"},"spec":{"commonName":"infra1-dc1-infra-k0s-k8s-kubernetes-front-proxy-ca","duration":"87600h","isCA":true,"issuerRef":{"kind":"Issuer","name":"infra1-dc1-infra-k0s-k8s-kubernetes-selfsigning-issuer"},"renewBefore":"8760h","secretName":"infra1-dc1-infra-k0s-k8s-kubernetes-pki-front-proxy-ca","subject":{"organizations":["infra1-dc1-infra-k0s-k8s-kubernetes"]},"usages":["signing","key
      encipherment","cert sign"]}}
  creationTimestamp: '2022-05-05T00:21:44Z'
  generation: 1
  labels:
    argocd.argoproj.io/instance: infra1-dc1-infra-k0s-k8s
  managedFields:
    - apiVersion: cert-manager.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:argocd.argoproj.io/instance': {}
        'f:spec':
          .: {}
          'f:commonName': {}
          'f:duration': {}
          'f:isCA': {}
          'f:issuerRef':
            .: {}
            'f:kind': {}
            'f:name': {}
          'f:renewBefore': {}
          'f:secretName': {}
          'f:subject':
            .: {}
            'f:organizations': {}
          'f:usages': {}
      manager: argocd-application-controller
      operation: Update
      time: '2022-05-05T00:21:44Z'
    - apiVersion: cert-manager.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:revision': {}
      manager: cert-manager-certificates-issuing
      operation: Update
      time: '2022-05-05T00:21:53Z'
    - apiVersion: cert-manager.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions':
            .: {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:observedGeneration': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:notAfter': {}
          'f:notBefore': {}
          'f:renewalTime': {}
      manager: cert-manager-certificates-readiness
      operation: Update
      time: '2022-05-05T00:21:54Z'
  name: infra1-dc1-infra-k0s-k8s-kubernetes-pki-front-proxy-ca
  namespace: core-prod
  resourceVersion: '1388400'
  uid: c6d47975-f991-4eb7-a2c7-9752385c615d
spec:
  commonName: infra1-dc1-infra-k0s-k8s-kubernetes-front-proxy-ca
  duration: 87600h0m0s
  isCA: true
  issuerRef:
    kind: Issuer
    name: infra1-dc1-infra-k0s-k8s-kubernetes-selfsigning-issuer
  renewBefore: 8760h0m0s
  secretName: infra1-dc1-infra-k0s-k8s-kubernetes-pki-front-proxy-ca
  subject:
    organizations:
      - infra1-dc1-infra-k0s-k8s-kubernetes
  usages:
    - signing
    - key encipherment
    - cert sign
status:
  conditions:
    - lastTransitionTime: '2022-05-05T00:21:53Z'
      message: Certificate is up to date and has not expired
      observedGeneration: 1
      reason: Ready
      status: 'True'
      type: Ready
  notAfter: '2032-05-02T00:21:50Z'
  notBefore: '2022-05-05T00:21:50Z'
  renewalTime: '2031-05-03T00:21:50Z'
  revision: 1
