{{- $fullName := include "kubernetes.fullname" . -}}
{{- $certName := include "kubernetes.certname" . -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infra1-dc1-infra-k0s-k8s-kubernetes-pki-front-proxy-ca
  namespace: core-prod
spec:
  commonName: infra1-dc1-infra-k0s-k8s-kubernetes-front-proxy-ca
  duration: 87600h0m0s
  isCA: true
  issuerRef:
    kind: Issuer
    name: infra1-dc1-infra-k0s-k8s-kubernetes-selfsigning-issuer
  renewBefore: 8760h0m0s
  secretName: infra1-dc1-infra-k0s-k8s-kubernetes-pki-front-proxy-ca
  subject:
    organizations:
      - infra1-dc1-infra-k0s-k8s-kubernetes
  usages:
    - signing
    - key encipherment
    - cert sign

