{{- $fullName := include "kubernetes.fullname" . -}}
{{- $certName := include "kubernetes.certname" . -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-pki-front-proxy-client

spec:
  commonName: {{ $certName }}-front-proxy-client

  duration: 8760h0m0s

  issuerRef:
    kind: Issuer
    name: {{ $fullName }}-front-proxy-issuer

  renewBefore: 4380h0m0s

  secretName: {{ $fullName }}-pki-front-proxy-client

  subject:
    organizations:
      - 'system:masters'

  usages:
    - signing
    - key encipherment
    - client auth

