{{- if .Values.tink.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  annotations: {}
  labels:
    app: {{ $fullName }}-tink-join-config

  name: {{ $fullName }}-tink-join-config
{{- end }}