{{- if and .Values.kubernetes.kine.enabled .Values.kubernetes.kine.service.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $fullName }}-kine
    {{- with .Values.kubernetes.kine.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  {{- with .Values.kubernetes.kine.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}


  name: {{ $fullName }}-kine
spec:
  type: {{ .Values.kubernetes.kine.service.type }}

  {{- with .Values.kubernetes.kine.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}

  allocateLoadBalancerNodePorts: true

  {{- with .Values.kubernetes.kine.service.externalIPs }}
  externalIPs:
  {{- range . }}
    - {{ . }}
  {{- end }}
  {{- end }}

  ports:
    - name: https

      targetPort: https
      port: 2379

      protocol: TCP
      appProtocol: https

  publishNotReadyAddresses: true
  sessionAffinity: ClientIP

  selector:
    app: {{ $fullName }}-kine
{{- end }}
