apiVersion: v1
kind: Service
metadata:
  labels:
    app: infra1-dc1-infra-k0s-k8s-kubernetes-kine

  name: infra1-dc1-infra-k0s-k8s-kubernetes-kine
  namespace: core-prod
spec:
  ports:
    - name: client
      port: 6443
  selector:
    app: infra1-dc1-infra-k0s-k8s-kubernetes-kine
  type: ClusterIP
