{{- $fullName := include "kubernetes.fullname" . -}}
{{- $certName := include "kubernetes.certname" . -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-pki-konnectivity-ca

spec:
  commonName: {{ $certName }}-konnectivity-ca

  secretName: {{ $fullName }}-pki-konnectivity-ca

  duration: 87600h0m0s
  renewBefore: 8760h0m0s

  subject:
    organizations:
    - {{ $fullName }}

  usages:
    - signing
    - key encipherment
    - cert sign

  isCA: true

  issuerRef:
    kind: Issuer
    name: {{ $fullName }}-selfsigning-issuer