{{- if or .Values.kubernetes.konnectivityServer.enabled .Values.kubernetes.konnectivityAgent.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
{{- $ipAddress := include "kubernetes.getKonnectivityAddress" . -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullName }}-konnectivitydeploy-tasks
  labels:
    app: {{ $fullName }}-konnectivitydeploy-tasks


spec:
  template:
    metadata:
      labels:
        app: {{ $fullName }}-konnectivitydeploy-tasks

    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: kubectl

          {{- with .Values.kubernetes.kubectl.image }}
          image: '{{ .repository }}{{ if .digest }}@{{ .digest }}{{ else }}:{{ .tag }}{{ end }}'
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}

          command: ['/scripts/deployKonnectivity.sh']

          env:
            - name: KUBECONFIG
              value: /etc/kubernetes/admin.conf

          volumeMounts:
            - name: kubeconfig
              mountPath: /etc/kubernetes/
              readOnly: true

            - name: pki-admin-client
              mountPath: /pki/admin-client

            - name: scripts
              mountPath: /scripts

            - mountPath: /manifests
              name: manifests
      volumes:
        - name: kubeconfig
          configMap:
            name: {{ $fullName }}-admin-conf
          

        - name: pki-admin-client
          secret:
            secretName: {{ $fullName }}-pki-admin-client
          

        - name: scripts
          configMap:
            name: {{ $fullName }}-konnectivitydeploy-scripts
            defaultMode: 0777
        
        - name: manifests
          projected:
            sources:
              - configMap:
                  name: {{ $fullName }}-konnectivity-manifests
{{- end }}
