apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infra1-dc1-infra-k0s-k8s-kubernetes-pki-konnectivity-client
spec:
  commonName: infra1-dc1-infra-k0s-k8s-kubernetes-konnectivity-client
  secretName: infra1-dc1-infra-k0s-k8s-kubernetes-pki-konnectivity-client

  duration: 8760h # 365d

  renewBefore: 4380h

  subject:
    organizations:
      - "system:masters"
  usages:
    - signing
    - key encipherment
    - client auth
  issuerRef:
    name: infra1-dc1-infra-k0s-k8s-kubernetes-konnectivity-issuer
    kind: Issuer
