{{- $fullName := include "kubernetes.fullname" . -}}
{{- $certName := include "kubernetes.certname" . -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-pki-konnectivity-client

spec:
  commonName: {{ $certName }}-konnectivity-client

  secretName: {{ $fullName }}-pki-konnectivity-client

  duration: 8760h0m0s

  renewBefore: 4380h0m0s

  subject:
    organizations:
      - system:masters

  usages:
    - signing
    - key encipherment
    - client auth

  issuerRef:
    kind: Issuer
    name: {{ $fullName }}-konnectivity-issuer