{{- if and .Values.kubernetes.konnectivityServer.enabled .Values.kubernetes.konnectivityServer.service.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-konnectivity-server

  labels:
    app: {{ $fullName }}-konnectivity-server

    {{- with .Values.kubernetes.konnectivityServer.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  annotations:
    {{- with .Values.kubernetes.konnectivityServer.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

spec:
  type: {{ .Values.kubernetes.konnectivityServer.service.type }}
  {{- with .Values.kubernetes.konnectivityServer.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}

  {{- with .Values.kubernetes.konnectivityServer.service.externalIPs }}
  externalIPs:
  {{- range . }}
    - {{ . }}
  {{- end }}
  {{- end }}

  ports:
    - name: server

      port: {{ .Values.kubernetes.konnectivityServer.service.ports.server }}

      protocol: TCP
      targetPort: server


    - name: agent

      port: {{ .Values.kubernetes.konnectivityServer.service.ports.agent }}
      protocol: TCP
      targetPort: agent

  selector:
    app: {{ $fullName }}-konnectivity-server
{{- end }}
