{{- $fullName := include "kubernetes.fullname" . -}}
{{- $certName := include "kubernetes.certname" . -}}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $fullName }}-konnectivity-issuer
spec:
  ca:
    secretName: {{ $fullName }}-pki-konnectivity-ca
