{{- if and .Values.kubernetes.konnectivityServer.enabled .Values.kubernetes.konnectivityServer.service.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-name: k0s-konnectivity
    metallb.universe.tf/allow-shared-ip: k0s-api

  labels:
    app: {{ $fullName }}-konnectivity-server

  name: {{ $fullName }}-konnectivity-server

spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack

  loadBalancerIP: 10.1.1.40

  externalIPs:
    - 10.1.1.41

  ports:
    - name: server

      port: {{ .Values.kubernetes.konnectivityServer.service.ports.server }}

      protocol: TCP
      targetPort: server


    - name: agent

      port: {{ .Values.kubernetes.konnectivityServer.service.ports.agent }}
      protocol: TCP
      targetPort: agent

  selector:
    app: {{ $fullName }}-konnectivity-server

  sessionAffinity: None
  type: LoadBalancer
{{- end }}