{{- $fullName := include "kubernetes.fullname" . -}}
{{- $certName := include "kubernetes.certname" . -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-pki-konnectivity-server

spec:
  commonName: {{ $certName }}-konnectivity-server

  secretName: {{ $fullName }}-pki-konnectivity-server

  duration: 8760h0m0s
  renewBefore: 4380h0m0s

  subject:
    organizations:
      - {{ $fullName }}

  usages:
  - 'signing'
  - 'key encipherment'
  - 'server auth'

  dnsNames:
    # Consul DNS Names
    - k0s-konnectivity
    - k0s-konnectivity.service
    - k0s-konnectivity.service.dc1
    - k0s-konnectivity.service.dc1.kjdev

    # Default Localhost
    - localhost

  ipAddresses:
    - 127.0.0.1

    # AnyCast
    - 10.1.1.41
    - 10.1.1.40

  issuerRef:
    name: {{ $fullName }}-konnectivity-issuer
    kind: Issuer
