{{- if .Values.kubernetes.admin.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-kubeadm-scripts

data:
  configure-cluster.sh: |+
    {{- tpl (.Files.Get "Scripts/configureCluster.sh") . | nindent 4 }}
{{- end }}