{{- if .Values.kubernetes.admin.job.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
{{- $ipAddress := include "kubernetes.getKonnectivityAddress" . -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $fullName }}-kubeadm-tasks

  labels:
    app: {{ $fullName }}-kubeadm-tasks

  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation

spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      annotations:
        checksum/config: ed81ca76edf6b6d372effdb9b0bf972f64d3fee0a4323beeae15a343b1340dd3
        checksum/scripts: 777431c8d69813d07e8ea5240ee8090152013441735e9c3147fefce0bcb4e008

      labels:
        app: {{ $fullName }}-kubeadm-tasks
    spec:
      template:
        metadata:
          labels:
            app: {{ $fullName }}-kubeadm-tasks

        spec:
          automountServiceAccountToken: false
          containers:
            - name: kubeadm

              image: registry.writemy.codes/tinkerbell/kubetools
              imagePullPolicy: IfNotPresent

              command:
                - /scripts/configure-cluster.sh

              env:
                - name: KUBECONFIG
                  value: /etc/kubernetes/admin.conf
              
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /etc/kubernetes/
                  name: kubeconfig
                  readOnly: true

                - mountPath: /pki/admin-client
                  name: pki-admin-client

                - mountPath: /scripts
                  name: scripts

                - mountPath: /manifests
                  name: manifests

                - mountPath: /config
                  name: config

          dnsPolicy: ClusterFirst

          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30

          volumes:
            - name: kubeconfig
              configMap:
                defaultMode: 420
                name: {{ $fullName }}-admin-conf

            - name: pki-admin-client
              secret:
                defaultMode: 420
                secretName: {{ $fullName }}-pki-admin-client

            - name: scripts
              configMap:
                defaultMode: 511
                name: {{ $fullName }}-kubeadm-scripts

            - name: manifests
              projected:
                defaultMode: 420
                sources:
                  - configMap:
                      name: >-
                        {{ $fullName }}-konnectivity-manifests

            - name: config
              configMap:
                defaultMode: 420
                name: {{ $fullName }}-kubeadm-config

  schedule: 0 0 1 */6 *
  successfulJobsHistoryLimit: 3
  suspend: false
{{- end }}
