apiVersion: v1
kind: ConfigMap
metadata:
  name: infra1-dc1-infra-k0s-k8s-kubernetes-kubeadm-config
  namespace: core-prod

data:
  kubeadmcfg.yaml: |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    controlPlaneEndpoint: 10.1.1.40:6443
    dns:
      imageRepository: 'kristianfjones/coredns-docker'
      imageTag: 'core0'

    featureGates:
      MixedProtocolLBService: true

    {{- with .Values.kubernetes.networking }}
    networking:
      dnsDomain: {{ .dnsDomain }}
      {{- with .podSubnet }}
      podSubnet: {{ . }}
      {{- end }}
      serviceSubnet: {{ .serviceSubnet }}
    {{- end }}
