apiVersion: v1
data:
  admin.conf: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /pki/admin-client/ca.crt
        server: https://infra1-dc1-infra-k0s-k8s-kubernetes-apiserver.core-prod.svc.cluster.local:6443
      name: default-cluster
    contexts:
    - context:
        cluster: default-cluster
        namespace: default
        user: default-auth
      name: default-context
    current-context: default-context
    kind: Config
    preferences: {}
    users:
    - name: default-auth
      user:
        client-certificate: /pki/admin-client/tls.crt
        client-key: /pki/admin-client/tls.key
kind: ConfigMap
metadata:
  name: infra1-dc1-infra-k0s-k8s-kubernetes-admin-conf
  namespace: core-prod
