{{- $fullName := include "kubernetes.fullname" . -}}
{{- $certName := include "kubernetes.certname" . -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-pki-sa

spec:
  commonName: {{ $certName }}-sa

  duration: 87600h0m0s

  isCA: true

  issuerRef:
    kind: Issuer
    name: {{ $fullName }}-selfsigning-issuer

  renewBefore: 8760h0m0s

  secretName: {{ $fullName }}-pki-sa

  subject:
    organizations:
      - {{ $fullName }}

  usages:
    - signing
    - key encipherment
    - cert sign
