apiVersion: v1
kind: ConfigMap
metadata:
  name: infra1-dc1-infra-k0s-k8s-kubernetes-kubeadm-scripts
  namespace: core-prod
data:
  configure-cluster.sh: |+
    {{- tpl (.Files.Get "scripts/configureCluster.sh") . | nindent 4 }}
