apiVersion: v1
kind: ConfigMap
metadata:
  name: infra1-dc1-infra-k0s-k8s-kubernetes-kubeadm-config
  namespace: core-prod

data:
  kubeadmcfg.yaml: |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    controlPlaneEndpoint: 10.1.1.40:6443
    networking:
      dnsDomain: k0s.resolvemy.host
      podSubnet: 10.4.0.0/16
      serviceSubnet: 10.0.8.0/22
