{{- $fullName := include "kubernetes.fullname" . -}}
{{- $apiAddress := include "kubernetes.getAPIHostnamePort" . -}}
---
apiVersion: v1
kind: ConfigMap

metadata:
  name: infra1-dc1-infra-k0s-k8s-kubernetes-scheduler-conf
  namespace: core-prod

data:
  scheduler.conf: |
    apiVersion: v1
    kind: Config
    clusters:
      - cluster:
          certificate-authority: /pki/scheduler-client/ca.crt
          server: https://{{ $apiAddress }}
        name: default-cluster

    contexts:
      - context:
          cluster: default-cluster
          namespace: default
          user: default-auth
        name: default-context

    current-context: default-context
    preferences: {}

    users:
      - name: default-auth
        user:
          client-certificate: /pki/scheduler-client/tls.crt
          client-key: /pki/scheduler-client/tls.key
