{{- if and .Values.kubernetes.scheduler.enabled .Values.kubernetes.scheduler.service.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $fullName }}-scheduler
  
  name: {{ $fullName }}-scheduler
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  
  ports:
    - name: client

      targetPort: 10259
      port: 10259

      protocol: TCP


  selector:
    app: {{ $fullName }}-scheduler

  sessionAffinity: None

  type: ClusterIP
{{- end }}