{{- $fullName := include "kubernetes.fullname" . -}}
{{- $certName := include "kubernetes.certname" . -}}
{{- $domains := splitList ".," (include "kubernetes.domains" .) -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-pki-scheduler-server

spec:
  commonName: {{ $certName }}-scheduler-server
  dnsNames:
    {{ range $domain := splitList ".," (include "kubernetes.domains" .) }}
    {{ $test := $domain | fromJson }}
    - {{ $fullName }}-scheduler{{ $test.domains | join "" }}
    - kubernetes{{ $test.domains | join "" }}
    {{ end }}
    - localhost
    - k0s-kubeapi.service.dc1.kjdev
    - k0s-kubeapi.service.kjdev
    - api.k0s.dc1.resolvemy.host


  duration: 8760h0m0s

  ipAddresses:
    - 127.0.0.1
    - 10.0.8.1
    - 172.18.213.183
    - 10.1.1.40

  issuerRef:
    kind: Issuer
    name: {{ $fullName }}-issuer

  renewBefore: 4380h0m0s

  secretName: {{ $fullName }}-pki-scheduler-server

  subject:
    organizations:
      - {{ $fullName }}

  usages:
    - signing
    - key encipherment
    - server auth
