{{- $fullName := include "kubernetes.fullname" . -}}
{{- $certName := include "kubernetes.certname" . -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-pki-scheduler-client

spec:

  commonName: 'system:kube-scheduler'

  duration: 8760h0m0s

  issuerRef:
    kind: Issuer
    name: {{ $fullName }}-issuer

  renewBefore: 4380h0m0s

  secretName: {{ $fullName }}-pki-scheduler-client

  subject:
    organizations:
      - 'system:kube-scheduler'

  usages:
    - signing
    - key encipherment
    - client auth
