apiVersion: v1
kind: Service
metadata:
  labels:
    app: infra1-dc1-infra-k0s-k8s-kubernetes-scheduler
  
  name: infra1-dc1-infra-k0s-k8s-kubernetes-scheduler
  namespace: core-prod
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  
  ports:
    - name: client

      targetPort: 10259
      port: 10259

      protocol: TCP


  selector:
    app: infra1-dc1-infra-k0s-k8s-kubernetes-scheduler

  sessionAffinity: None

  type: ClusterIP
