kind: ConfigMap
metadata:
  name: infra1-dc1-infra-k0s-k8s-tink-manifests
  namespace: core-prod

apiVersion: v1

data:
{{- range untilStep (.Values.relay.min|int) (.Values.relay.max|int) 1 }}
    - port: {{ . }}
      targetPort: {{ . }}
      protocol: UDP
      name: 'udp-{{ . }}'

    - port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
      name: 'tcp-{{ . }}'
{{ end }}
