{{- if .Values.tink.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-tink-sync-scripts

data:
  tinkSync.sh: |+
    {{- tpl (.Files.Get "Scripts/tinkSync.sh") . | nindent 4 }}
{{- end }}
