kind: ConfigMap
metadata:
  name: infra1-dc1-infra-k0s-k8s-tink-manifests
  namespace: core-prod

apiVersion: v1

data:
{{- $ignitionFile := (.Files.Get "Scripts/Ignition.yaml") }}
{{- range $index, $machine :=  .Values.tink.machines }}
  {{ printf "%d-tinkhardware.yaml" $index }}: |
    apiVersion: "tinkerbell.org/v1alpha1"
    kind: Hardware
    metadata:
      name: '{{ $machine.Name }}-core'
    spec:
      metadata:
        facility:
          facility_code: onprem
        manufacturer:
          slug: supermicro
        instance:
          userdata: ""
          hostname: {{ $machine.Name }}
          id: {{ $machine.MAC }}
          operating_system:
            distro: "ubuntu"
            os_slug: "ubuntu_20_04"
            version: "20.04"
      interfaces:
        - dhcp:
            arch: amd64
            hostname: {{ $machine.Name }}
            ip:
              address: {{ $machine.IPAddress }}
              gateway: 172.16.20.254
              netmask: 255.255.255.0
            lease_time: 86400
            mac: {{ $machine.MAC }}
            name_servers:
              - 10.0.8.10
            uefi: true
          netboot:
            allowPXE: true
            allowWorkflow: true
  {{ printf "%d-tinkworkflow.yaml" $index }}: |
    apiVersion: "tinkerbell.org/v1alpha1"
    kind: Workflow
    metadata:
      name: '{{ $machine.Name }}-wf'
    spec:
      templateRef: kubernetes
      hardwareMap:
        machine1: {{ $machine.MAC }}
        
        version: '{{ $ignitionFile | b64enc  }}'
{{- end }}
