apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: infra1-dc1-infra-k0s-k8s-tink-sync-tasks
  name: infra1-dc1-infra-k0s-k8s-tink-sync-tasks
  namespace: core-prod
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        app: infra1-dc1-infra-k0s-k8s-tink-sync-tasks
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: infra1-dc1-infra-k0s-k8s-tink-sync-tasks
        spec:
          automountServiceAccountToken: false
          containers:
            - name: kubeadm

              image: registry.writemy.codes/tinkerbell/kubetools
              imagePullPolicy: IfNotPresent

              command:
                - /scripts/tinkSync.sh

              env:
                - name: KUBECONFIG
                  value: /etc/kubernetes/admin.conf
              
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /etc/kubernetes/
                  name: kubeconfig
                  readOnly: true

                - mountPath: /pki/admin-client
                  name: pki-admin-client

                - mountPath: /scripts
                  name: scripts

                - mountPath: /manifests
                  name: manifests

                - mountPath: /config
                  name: config

          dnsPolicy: ClusterFirst

          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30

          volumes:
            - configMap:
                defaultMode: 420
                name: infra1-dc1-infra-k0s-k8s-kubernetes-admin-conf
              name: kubeconfig

            - name: pki-admin-client
              secret:
                defaultMode: 420
                secretName: infra1-dc1-infra-k0s-k8s-kubernetes-pki-admin-client

            - configMap:
                defaultMode: 511
                name: infra1-dc1-infra-k0s-k8s-tink-sync-scripts
              name: scripts

            - name: manifests
              projected:
                defaultMode: 420
                sources:
                  - configMap:
                      name: infra1-dc1-infra-k0s-k8s-tink-manifests

            - configMap:
                defaultMode: 420
                name: infra1-dc1-infra-k0s-k8s-kubernetes-kubeadm-config
              name: config

  schedule: 0 0 1 */6 *
  successfulJobsHistoryLimit: 3
