{{- if .Values.tink.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $fullName }}-tink-sync-tasks

  labels:
    app: {{ $fullName }}-tink-sync-tasks

spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        app: {{ $fullName }}-tink-sync-tasks

    spec:
      template:
        metadata:
          labels:
            app: {{ $fullName }}-tink-sync-tasks

        spec:
          automountServiceAccountToken: false
          containers:
            - name: kubeadm

              image: registry.writemy.codes/tinkerbell/kubetools
              imagePullPolicy: IfNotPresent

              command:
                - /scripts/tinkSync.sh

              env:
                - name: KUBECONFIG
                  value: /etc/kubernetes/admin.conf
              
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /etc/kubernetes/
                  name: kubeconfig
                  readOnly: true

                - mountPath: /pki/admin-client
                  name: pki-admin-client

                - mountPath: /scripts
                  name: scripts

                - mountPath: /manifests
                  name: manifests

                - mountPath: /config
                  name: config

                - name: ignition-config
                  mountPath: /etc/ignition.yaml
                  subPath: ignition.yaml

          dnsPolicy: ClusterFirst

          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30

          volumes:
            - name: kubeconfig
              configMap:
                defaultMode: 420
                name: {{ $fullName }}-admin-conf
              

            - name: pki-admin-client
              secret:
                defaultMode: 420
                secretName: {{ $fullName }}-pki-admin-client

            - name: ignition-config
              secret:
                defaultMode: 420
                secretName: core0-ignition-config

            - name: scripts
              configMap:
                defaultMode: 511
                name: {{ $fullName }}-tink-sync-scripts

            - name: manifests
              projected:
                defaultMode: 420
                sources:
                  - configMap:
                      name: {{ $fullName }}-tink-manifests

            - name: config
              configMap:
                defaultMode: 420
                name: {{ $fullName }}-kubeadm-config
              

  schedule: 0 0 1 */6 *
  successfulJobsHistoryLimit: 3
{{- end }}