apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: pomerium-ca
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pomerium-ca
spec:
  isCA: true
  secretName: pomerium-ca
  commonName: pomerium ca
  issuerRef:
    name: pomerium-ca
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: pomerium-issuer
spec:
  ca:
    secretName: pomerium-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pomerium-cert
spec:
  secretName: pomerium-tls
  issuerRef:
    name: pomerium-issuer
    kind: Issuer
  usages:
    - server auth
    - client auth
  dnsNames:
    - pomerium-core-proxy.core-prod.svc.cluster.local
    - pomerium-core-authorize.core-prod.svc.cluster.local
    - pomerium-core-databroker.core-prod.svc.cluster.local
    - pomerium-core-authenticate.core-prod.svc.cluster.local
    - authenticate.int.mylogin.space
