{{- if .Values.tink.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{ $fullName }}-tink-token-generator

  name: {{ $fullName }}-tink-token-generator

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullName }}-tink-token-generator

subjects:
  - kind: ServiceAccount
    name: {{ $fullName }}-tink-token-generator
    namespace: {{ .Release.Namespace }}
{{- end }}