{{- if .Values.tink.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: {{ $fullName }}-tink-token-generator

  name: {{ $fullName }}-tink-token-generator
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ $fullName }}-tink-token-generator

        spec:
          containers:
            - name: kubeadm

              image: registry.writemy.codes/tinkerbell/kubetools
              imagePullPolicy: IfNotPresent

              command:
                - /scripts/genToken.sh
              env:

                - name: SVC
                  value: {{ $fullName }}-apiserver

                - name: SECRET
                  value: core0-ignition-config

              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi

              volumeMounts:
                - mountPath: /etc/kubernetes/
                  name: kubeconfig
                  readOnly: true

                - mountPath: /scripts
                  name: scripts

                - mountPath: /pki/admin-client
                  name: pki-admin-client

                - name: ignition
                  mountPath: /etc/ignition.yaml
                  subPath: ignition.yaml

          restartPolicy: OnFailure
          serviceAccountName: {{ $fullName }}-tink-token-generator


          volumes:
            - configMap:
                defaultMode: 420
                name: {{ $fullName }}-admin-conf
              name: kubeconfig

            - configMap:
                defaultMode: 511
                name: {{ $fullName }}-tink-token-generator-scripts
              name: scripts

            - configMap:
                name: {{ $fullName }}-tink-ignition-manifests
              name: ignition

            - name: pki-admin-client
              secret:
                secretName: {{ $fullName }}-pki-admin-client
  schedule: 0 */12 * * *
{{- end }}