{{- if .Values.tink.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-tink-token-generator-scripts

data:
  genToken.sh: |+
    {{- .Files.Get "Scripts/genToken.sh" | nindent 4 }}
{{- end }}