{{- if .Values.tink.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations: {}
  labels:
    app: {{ $fullName }}-tink-token-generator

  name: {{ $fullName }}-tink-token-generator
rules:
  - apiGroups:
      - ''

    resourceNames:
      - {{ $fullName }}-apiserver

    resources:
      - services

    verbs:
      - get
      - watch

  - apiGroups:
      - ''

    resourceNames:
      - core0-ignition-config

    resources:
      - secrets

    verbs:
      - get
      - patch
      - create
      - update
      - delete
{{- end }}