apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: infra1-dc1-infra-k0s-token-generator

  name: infra1-dc1-infra-k0s-token-generator
  namespace: core-prod

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infra1-dc1-infra-k0s-token-generator

subjects:
  - kind: ServiceAccount
    name: infra1-dc1-infra-k0s-token-generator
    namespace: core-prod
