{{- if .Values.kubernetes.virtual.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: vcluster

  name: vc-workload-{{ $fullName }}
{{- end }}
