{{- if .Values.kubernetes.virtual.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
{{- $certName := include "kubernetes.certname" . -}}
{{- $domains := splitList ".," (include "kubernetes.domains" .) -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-pki-vcluster-syncer-server

spec:
  commonName: '{{ $certName }}-vcluster-syncer-server'

  dnsNames:
    {{ range $domain := splitList ".," (include "kubernetes.domains" .) }}
    {{ $test := $domain | fromJson }}
    - {{ $fullName }}-vcluster-syncer{{ $test.domains | join "" }}
    - kubernetes{{ $test.domains | join "" }}
    {{ end }}
    - localhost
  
  duration: 8760h0m0s
  
  ipAddresses:
    {{- with .Values.kubernetes.apiServer.service.loadBalancerIP }}
    {{- if not (has . $.Values.kubernetes.apiServer.certSANs.ipAddresses) }}
    - {{ . | quote }}
    {{- end }}
    {{- end }}
    {{- with .Values.kubernetes.apiServer.certSANs.ipAddresses }}
    {{- range . }}
      - {{ . }}
    {{- end }}
    {{- end }}
  
  issuerRef:
    kind: Issuer
    name: '{{ $fullName }}-issuer'
  
  renewBefore: 4380h0m0s
  
  secretName: '{{ $fullName }}-pki-vcluster-syncer-server'
  
  subject:
    organizations:
      - '{{ $fullName }}'
  
  usages:
    - signing
    - key encipherment
    - server auth
{{- end }}
