{{- if .Values.kubernetes.virtual.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: vcluster

  name: vc-infra1-dc1-infra-k0s-k8s
  namespace: core-prod
{{- end }}
