{{- $fullName := include "kubernetes.fullname" . -}}
{{- $apiAddress := include "kubernetes.getAPIHostnamePort" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-vcluster-syncer-conf

data:
  admin.conf: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /pki/vcluster-syncer/ca.crt
        server: https://{{ $apiAddress }}
      name: default-cluster
    contexts:
    - context:
        cluster: default-cluster
        namespace: default
        user: default-auth
      name: my-vcluster
    current-context: my-vcluster
    kind: Config
    preferences: {}
    users:
    - name: default-auth
      user:
        client-certificate: /pki/vcluster-syncer/tls.crt
        client-key: /pki/vcluster-syncer/tls.key
