{{- if .Values.kubernetes.virtual.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: vcluster

  name: vc-{{ $fullName }}-vcluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vc-{{ $fullName }}-vcluster

subjects:
  - kind: ServiceAccount
    name: vc-{{ $fullName }}
    namespace: {{ $fullName }}
{{- end }}
