{{- if .Values.kubernetes.virtual.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: vcluster

  name: {{ $fullName }}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullName }}
subjects:
  - kind: ServiceAccount
    name: vc-{{ $fullName }}
    namespace: {{ .Release.Namespace }}
{{- end }}
