{{- $fullName := include "capi.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-ext

  labels:
    control-plane: controller-manager

spec:
  selector:
    matchLabels:
      control-plane: controller-manager

  replicas: 1

  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager

    spec:
      securityContext:
        runAsNonRoot: true

      containers:
        - name: kube-rbac-proxy
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
          args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10

          ports:
            - containerPort: 8443
              protocol: TCP
              name: https

        - name: manager
          command:
            - /manager

          args:
            - run
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect

          image: docker.io/erwinvaneyk/cluster-api-external-controller
          
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 9440
              name: healthz
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz

          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 5
            periodSeconds: 10

          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: {{ $fullName }}-ext
      terminationGracePeriodSeconds: 10
