apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# replicas:
#   - name: k0s-cntrl-rdns-lab-hello-world
#     count: 5

patchesJson6902:
  - target:
      group: "apps" 
      version: v1 # apiVersion
      kind: StatefulSet
      name: infra1-dc1-infra-k0s-k8s-kubernetes-etcd
    path: merger.yaml
