apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: infra1-dc1-infra-k0s-k8s-kubernetes-etcd
spec:
  template:
    spec:
      initContainers:
        - name: init-etcd
          image: k8s.gcr.io/etcd:3.5.1-0
          volumeMounts:
            - mountPath: /pki/etcd/ca
              name: pki-etcd-certs-ca
            - mountPath: /pki/etcd/peer
              name: pki-etcd-certs-peer
            - mountPath: /pki/etcd/server
              name: pki-etcd-certs-server
            - mountPath: /var/lib/etcd
              name: etcd-data
            - mountPath: /backup/snapshot.db
              name: etcd-snapshot
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCDCTL_API
              value: '3'
            - name: ETCDCTL_CACERT
              value: /pki/etcd/peer/ca.crt
            - name: ETCDCTL_CERT
              value: /pki/etcd/peer/tls.crt
            - name: ETCDCTL_KEY
              value: /pki/etcd/peer/tls.key
            - name: ETCDCTL_ENDPOINTS
              value: >-
                https://infra1-dc1-infra-k0s-k8s-kubernetes-etcd-0.infra1-dc1-infra-k0s-k8s-kubernetes-etcd:2379,https://infra1-dc1-infra-k0s-k8s-kubernetes-etcd-1.infra1-dc1-infra-k0s-k8s-kubernetes-etcd:2379,https://infra1-dc1-infra-k0s-k8s-kubernetes-etcd-2.infra1-dc1-infra-k0s-k8s-kubernetes-etcd:2379

          command:
            - etcdctl
            - snapshot
            - restore
            - /backup/snapshot.db
            - '--cert=/pki/etcd/server/tls.crt'
            - '--data-dir=/var/lib/etcd'
            - >-
              --initial-advertise-peer-urls=https://$(POD_NAME).infra1-dc1-infra-k0s-k8s-kubernetes-etcd:2380
            - >-
              --initial-cluster=infra1-dc1-infra-k0s-k8s-kubernetes-etcd-0=https://infra1-dc1-infra-k0s-k8s-kubernetes-etcd-0.infra1-dc1-infra-k0s-k8s-kubernetes-etcd:2380,infra1-dc1-infra-k0s-k8s-kubernetes-etcd-1=https://infra1-dc1-infra-k0s-k8s-kubernetes-etcd-1.infra1-dc1-infra-k0s-k8s-kubernetes-etcd:2380,infra1-dc1-infra-k0s-k8s-kubernetes-etcd-2=https://infra1-dc1-infra-k0s-k8s-kubernetes-etcd-2.infra1-dc1-infra-k0s-k8s-kubernetes-etcd:2380
            - '--initial-cluster-token=infra1-dc1-infra-k0s-k8s-kubernetes-etcd'
            - '--key=/pki/etcd/server/tls.key'
            - '--name=$(POD_NAME)'
            - '--ca=/pki/etcd/ca/tls.crt'
