apiVersion: apps/v1
kind: Deployment
metadata:
  name: cntrlplane-certmanager-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: webhook
      app.kubernetes.io/instance: infra1-dc1-cntrlplane
      app.kubernetes.io/name: webhook
  template:
    metadata:
      labels:
        app: webhook
        app.kubernetes.io/component: webhook
        app.kubernetes.io/instance: infra1-dc1-cntrlplane
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: webhook
        app.kubernetes.io/version: v1.8.2
        helm.sh/chart: cert-manager-v1.8.2
    spec:
      containers:
        - args:
            - '--v=2'
            - '--secure-port=10250'
            - '--dynamic-serving-ca-secret-namespace=$(POD_NAMESPACE)'
            - '--dynamic-serving-ca-secret-name=cntrlplane-certmanager-webhook-ca'
            - >-
              --dynamic-serving-dns-names=cntrlplane-certmanager-webhook,cntrlplane-certmanager-webhook.core-prod,cntrlplane-certmanager-webhook.core-prod.svc
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: 'quay.io/jetstack/cert-manager-webhook:v1.8.2'
          imagePullPolicy: IfNotPresent

          name: cert-manager
          ports:
            - containerPort: 10250
              name: https
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 6080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      serviceAccountName: default
      volumes:
        - name: kubeconfig
          secret:
            defaultMode: 420
            secretName: infra1-dc1-cntrlplane-kubeconfig