apiVersion: apps/v1
kind: Deployment
metadata:
  name: cntrlplane-certmanager-webhook

spec:
  replicas: 1
  template:
    spec:
      containers:
        - args:
            - '--v=2'
            - '--secure-port=10250'
            - '--dynamic-serving-ca-secret-namespace=$(POD_NAMESPACE)'
            - '--kubeconfig=/var/run/kubeconfig'
            - '--dynamic-serving-ca-secret-name=cntrlplane-certmanager-webhook-ca'
            - >-
              --dynamic-serving-dns-names=cntrlplane-certmanager-webhook,cntrlplane-certmanager-webhook.core-prod,cntrlplane-certmanager-webhook.core-prod.svc

          name: cert-manager
          volumeMounts:
            - mountPath: /var/run/kubeconfig
              name: kubeconfig
              subPath: kubeconfig

      volumes:
        - name: kubeconfig
          secret:
            defaultMode: 420
            secretName: infra1-dc1-cntrlplane-kubeconfig