apiVersion: apps/v1
kind: Deployment
metadata:
  name: cntrlplane-certmanager-webhook
  namespace: core-prod
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: infra1-dc1-cntrlplane
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: webhook
    app.kubernetes.io/version: v1.8.2
    argocd.argoproj.io/instance: infra1-dc1-cntrlplane
    helm.sh/chart: cert-manager-v1.8.2

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: webhook
      app.kubernetes.io/instance: infra1-dc1-cntrlplane
      app.kubernetes.io/name: webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webhook
        app.kubernetes.io/component: webhook
        app.kubernetes.io/instance: infra1-dc1-cntrlplane
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: webhook
        app.kubernetes.io/version: v1.8.2
        helm.sh/chart: cert-manager-v1.8.2
    spec:
      containers:
        - name: cert-manager
          volumeMounts:
            - mountPath: /var/run/kubeconfig
              name: kubeconfig
              subPath: kubeconfig
      volumes:
        - name: kubeconfig
          secret:
            defaultMode: 420
            secretName: infra1-dc1-cntrlplane-kubeconfig