apiVersion: v2

version: 1.0.0

name: core-cntrl-plane

dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: 1.x.x

  - name: liqo
    version: 0.5.0-beta.2
    condition: liqo.enabled
    repository: https://helm.liqo.io/

  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
