apiVersion: v2

version: 1.0.0

name: core-cntrl-plane

dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: 1.x.x

  - name: external-secrets
    repository: https://charts.external-secrets.io
    version: 0.5.x

  - name: crossplane
    repository: https://charts.crossplane.io/master/
    version: 1.9.0-rc.0.9.g243f1f47

  - name: vela-core
    repository: https://charts.kubevela.net/core
    version: 1.5.0-nightly-build

  - name: liqo
    version: 0.5.0-beta.2
    condition: liqo.enabled
    repository: https://helm.liqo.io/

  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
