{{- if .Values.istiod.ingress.enabled }}
{{- $fullName := include "cntrlmesh.fullname" . -}}
{{- $gwURL := include "cntrlmesh.istio.gwURL" . -}}
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-config

  namespace: istio-system
spec:
  defaultRevision: false
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true

        k8s:
          serviceAnnotations:
            external-dns.alpha.kubernetes.io/hostname: {{ $gwURL }}

          overlays:
            - kind: Service
              name: istio-ingressgateway
              patches:
                - path: metadata.labels.lan-mode
                  value: private

          service:
            type: ClusterIP
            ports:
              - port: 15010
                targetPort: 15010
                name: grpc-xds

              - port: 15021
                targetPort: 15021
                name: status-port

              - port: 15012
                targetPort: 15012
                name: tls-xds

              - port: 15014
                targetPort: 15014
                name: http-monitor

              - port: 15017
                targetPort: 15017
                name: tls-webhook

{{- end }}
