apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-config
spec:
  defaultRevision: false
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        # label:
        #   lan-mode: private
        k8s:
          serviceAnnotations:
            external-dns.alpha.kubernetes.io/hostname: '{{ .Values.url }}'
          type: ClusterIP

          service:
            ports:
              - port: 15021
                targetPort: 15021
                name: status-port

              - port: 15012
                targetPort: 15012
                name: tls-xds

              - port: 15014
                targetPort: 15014
                name: http-monitor

              - port: 15017
                targetPort: 15017
                name: tls-webhook
