{{- if .Values.istiod.istiod.enabled }}
{{- $fullName := include "cntrlmesh.fullname" . -}}
{{- $gwURL := include "cntrlmesh.istio.gwURL" . -}}
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiod

  namespace: external-istiod
spec:
  defaultRevision: true

  profile: empty
  
  #
  # https://preliminary.istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/
  #
  meshConfig:
    accessLogFile: /dev/stdout
    defaultProviders:
      accessLogging:
        - envoy
        - otel



    rootNamespace: external-istiod

    trustDomain: k0s.resolvemy.host

    outboundTrafficPolicy:
      mode: ALLOW_ANY

    extensionProviders:
      - name: otel
        envoyOtelAls:
          service: otel-core.core-prod.svc.k0s.resolvemy.host
          port: 4317

      - name: 'authentik'
        envoyExtAuthzHttp:
          service: k0s-cntrl-aaa-authentik.core-prod.svc.k0s.resolvemy.host
          port: '80'
          pathPrefix: '/outpost.goauthentik.io/auth/envoy'
          headersToDownstreamOnAllow:
            - cookie
          headersToUpstreamOnAllow:
            - set-cookie
            - x-authentik-*
            - x-remote-*
          includeRequestHeadersInCheck:
            - cookie

    defaultConfig:
      discoveryAddress: {{ $gwURL }}:15012
    
      tracing:
        sampling: 0.25
        zipkin:
          address: otel-core.core-prod.svc.k0s.resolvemy.host:9411

      proxyMetadata:
        XDS_ROOT_CA: /etc/ssl/certs/ca-certificates.crt
        CA_ROOT_CA: /etc/ssl/certs/ca-certificates.crt

  components:
    ingressGateways:
      - name: istio-gw
        enabled: true

        label:
          istio: istio-gw

        k8s:
          serviceAnnotations:
            external-dns.alpha.kubernetes.io/hostname: {{ $gwURL }}

          overlays:
            - kind: Service
              name: istio-gw
              patches:
                - path: metadata.labels.lan-mode
                  value: private

            - kind: Deployment
              name: istio-gw
              patches:
                - path: spec.template.spec.hostAliases
                  value:
                    - ip: 172.18.143.30
                      hostnames:
                        - istio.mylogin.space

                - path: spec.template.spec.containers.[name:istio-proxy].env.[100]
                  value: |
                    name: CA_ROOT_CA
                    value: /var/run/secrets/istio/root-cert.pem

                - path: spec.template.spec.containers.[name:istio-proxy].env.[100]
                  value: |
                    name: XDS_ROOT_CA
                    value: /var/run/secrets/istio/root-cert.pem

          service:
            type: ClusterIP
            ports:
              - port: 15010
                targetPort: 15010
                name: grpc-xds

              - port: 15021
                targetPort: 15021
                name: status-port

              - port: 15012
                targetPort: 15012
                name: tls-xds

              - port: 15014
                targetPort: 15014
                name: http-monitor

              - port: 15017
                targetPort: 15017
                name: tls-webhook

    pilot:
      enabled: true
      k8s:
        overlays:
          - kind: Deployment
            name: istiod
            patches:
              - path: spec.template.spec.volumes.[-1]
                value:
                  name: public-tls
                  secret:
                    secretName: {{ $fullName }}-gw-certs

              - path: spec.template.spec.containers.[name:discovery].volumeMounts.[-1]
                value:
                  name: public-tls
                  mountPath: /etc/tls/istio


              - path: spec.template.metadata.labels.logs
                value: loki-myloginspace

              - path: metadata.labels.argocd.argoproj.io/instance
                value: cntrl-plane-infra-k0s-istiod

              - path: spec.template.spec.containers.[name:discovery].args.[100]
                value: '--tlsCertFile=/etc/tls/istio/tls.crt'

              - path: spec.template.spec.containers.[name:discovery].args.[100]
                value: '--tlsKeyFile=/etc/tls/istio/tls.key'
        env:
          - name: ENABLE_DEBUG_ON_HTTP
            value: 'true'

          - name: EXTERNAL_ISTIOD
            value: 'true'

          - name: ISTIOD_CUSTOM_HOST
            value: 'istio.mylogin.space,istiod.external-istiod.svc.k0s-lab.resolvemy.host'

          - name: ISTIOD_ADDR
            value: 'istio.mylogin.space:15012'

          - name: PILOT_ENABLE_QUIC_LISTENERS
            value: 'true'

          - name: PILOT_USE_ENDPOINT_SLICE
            value: 'true'
          
          - name: ISTIO_GATEWAY_STRIP_HOST_PORT
            value: 'true'

          - name: BOOTSTRAP_XDS_AGENT
            value: 'true'

          - name: PROXY_CONFIG_XDS_AGENT
            value: 'true'

  values:
    global:
      #################
      #               #
      #     MAIN      #
      #               #
      #################

      #
      # Multi Cluster
      #
      meshID: mesh1

      multiCluster:
        enabled: true
        clusterName: cntrlplane
        includeEnvoyFilter: true


      network: network1

       
      ##########################
      #
      #          Misc
      #
      ###########################

      istioNamespace: external-istiod

      #
      # Controls whether the server-side validation is enabled
      #
      configValidation: false

      ################
      #   Webhooks   #
      ################

      operatorManageWebhooks: false

      ###############
      #   Logging   #
      ###############
      logAsJson: true
      logging:
        level: 'default:info'

      #
      # TLS
      #
      caAddress: {{ $gwURL }}:15012

      #pilotCertProvider: kubernetes

      


      proxy:
        clusterDomain: k0s.resolvemy.host

        logLevel: info

        resources:
          requests:
            cpu: 64m
            memory: 32Mi
          limits: null

    istiodRemote:
      injectionURL: >-
        https://istiod.external-istiod.svc.k0s-lab.resolvemy.host:443/inject/:ENV:cluster=cntrlplane:ENV:net=network1


{{- end }}
