{{- if .Values.istiod.ingress.enabled }}
{{- $fullName := include "cntrlmesh.fullname" . -}}
{{- $gwURL := include "cntrlmesh.istio.gwURL" . -}}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ $fullName }}-ext-gw
  namespace: external-istiod

spec:
  selector:
    istio: istio-gw

  servers:
    - port:
        number: 15010
        protocol: grpc
        name: grpc-XDS

      hosts:
        - {{ $gwURL }}


    - port:
        number: 15012
        protocol: https
        name: https-XDS

      tls:
        mode: SIMPLE
        credentialName: {{ $fullName }}-gw-certs

      hosts:
        - {{ $gwURL }}


    - port:
        number: 15017
        protocol: https
        name: https-WEBHOOK

      tls:
        mode: PASSTHROUGH
      hosts:
        - {{ $gwURL }}


    - port:
        number: 15014
        protocol: https
        name: https-MONITOR

      tls:
        mode: SIMPLE
        credentialName: {{ $fullName }}-gw-certs

      hosts:
        - {{ $gwURL }}

{{- end }}
