apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: external-istiod-gw
  namespace: external-istiod

spec:
  selector:
    istio: ingressgateway

  servers:
    - port:
        number: 15012
        protocol: https
        name: https-XDS
      tls:
        mode: SIMPLE
        credentialName: external-istiod-gw-certs
      hosts:
        - {{ .Values.url }}

    - port:
        number: 15017
        protocol: https
        name: https-WEBHOOK
      tls:
        mode: SIMPLE
        credentialName: external-istiod-gw-certs
      hosts:
        - {{ .Values.url }}

    - port:
        number: 15014
        protocol: https
        name: https-MONITOR
      tls:
        mode: SIMPLE
        credentialName: external-istiod-gw-certs
      hosts:
        - {{ .Values.url }}
