{{- if .Values.istiod.ingress.enabled }}
{{- $fullName := include "cntrlmesh.fullname" . -}}
{{- $gwURL := include "cntrlmesh.istio.gwURL" . -}}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
   name: {{ $fullName }}-ext-gw
spec:
  hosts:
    - {{ $gwURL }}

  gateways:
    - {{ $fullName }}-ext-gw

  http:
    #
    # XDS and CA services (Plaintext, only for secure networks)	
    #
    - match:
        - port: 15010
      route:
        - destination:
            host: istiod.external-istiod.svc.cluster.local
            port:
              number: 15010


    #
    # XDS and CA services (TLS and mTLS, recommended for production use)	
    #

    - match:
        - port: 15012
      route:
        - destination:
            host: istiod.external-istiod.svc.cluster.local
            port:
              number: 15012


    #
    # Control plane monitoring
    #

    - match:
        - port: 15014
      route:
        - destination:
            host: istiod.external-istiod.svc.cluster.local
            port:
              number: 15014


    #
    # Webhook container port, forwarded from 443	
    #
  tls:
    - match:
        - port: 15017
          sniHosts:
            - {{ $gwURL }}
      route:
        - destination:
            host: istiod.external-istiod.svc.cluster.local
            port:
              number: 443
{{- end }}
